language: perl
sudo: false
perl:
  - "5.16"
  - "5.10"
before_install:
    - "git clone https://github.com/Ensembl/ensembl-hive.git ~/ensembl-hive"
    - "git clone https://github.com/Ensembl/ensembl-io.git ~/ensembl-io"
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"
env:
  global:
    -PERL5LIB=$PERL5LIB:~/ensembl-hive/modules:~/ensembl-io/modules  
script:
  perl Build.PL && ./Build build && cover -test -report coveralls